### PR TITLE
just send params to create bundle config

### PR DESCRIPTION
**Pull request by mpeck**
`params` already includes the `config` key and there are additional bits that also need to be passed outside of config that influence bundle creation. For example the enabling of bundles during creation.

This is causing test failures in cogctl.

### CODE REVIEW

**Comment by kevsmith** [comment]
Is this purely an internal change to cog-api-client or will consumers of the lib need to update code?

**Comment by mpeck** [comment]
Consumers may need to update code. I'm looking though Flywheel now to see if there are any places that will be affected by it.

**Comment by mpeck** [comment]
With the updates to Flywheel, is this ok to merge?

**Comment by kevsmith** [comment]
LGTM

**Pull request merged**
