### PR TITLE
Fix a few issues with Dialzyer setup

### PR DESCRIPTION
**Pull request by drapergeek**
* Make the `bin/rebuild_plt` script executable
* Check for an existing plt file before attempting to delete it
* Fix a problem that dialyzer found with the `Role.show` in client!
* Add a few missing callbacks now that dialyzer seems to be useful.

### CODE REVIEW

**Comment by jsteiner** [comment]
It looks like the [exit status of dialyzer](http://erlang.org/doc/man/dialyzer.html) is this:

```
0 - No problems were encountered during the analysis and no
          warnings were emitted.
1 - Problems were encountered during the analysis.
2 - No problems were encountered, but warnings were emitted.
```

With elixir updated, would we be able to run dialyzer on Circle and fail if we get a 1 or 2?

**Comment by drapergeek** [comment]
LIES!!

```
cog-api-client jd-dialyzer % mix dialyzer
lib/cog_api/fake/client.ex:36: warning: variable endpoint is unused
lib/cog_api/fake/client.ex:36: warning: variable name is unused
Compiled lib/cog_api/fake/client.ex
Starting Dialyzer
dialyzer --no_check_plt --plt .dialyzer.plt -Wunderspecs -Wno_undefined_callbacks /Users/draper/code/operable/cog-api-client/_build/dev/lib/cog_api/ebin
  Compiling some key modules to native code... done in 0m0.25s
  Proceeding with analysis...
client.ex:36: The inferred return type of permission_create/2 ('nil') has nothing in common with {atom(),#{}}, which is the expected return type for the callback of 'Elixir.CogApi.Client' behaviour
 done in 0m1.08s
done (warnings were emitted)

cog-api-client jd-dialyzer % echo $!
0
```

**Comment by drapergeek** [comment]
My guess is that the mix task that wraps dialyzer is not returning that properly and instead, it returns the mix task status.

**Comment by jsteiner** [comment]
Nope. Tried it without the mix task and same deal ¯\_(ツ)_/¯

**Comment by jsteiner** [comment]
LGTM. We can look into this some more later

**Pull request merged**
